### PR TITLE
[tex.rst] document wikimedia-texvc.js

### LINKED ISSUE #87: document wikipedia-texvc extension

### PR DESCRIPTION
**Pull request by pkra**
Fixes #87

### CODE REVIEW

**Comment by pkra** [comment]
This PR is a bit bigger so I'd rather not merge myself. @dpvc @zorkow could you take a look?

**Comment by dpvc** [comment]
I'm wondering if we should push the `wikimedia-texvc` extension to `[Contrib]` rather than core.  Many of their definitions are non-standard in the sense that they are not part of any LaTeX package that we are emulating (e.g., `\Complex` and `\cnums`), and I am concerned a bit about listing them in the list of supported TeX macros (especially without a `non-standard` marker).  What do you think?

**Comment by pkra** [comment]
IIRC, the rationale to add the extension to the core was that it simplifies deployment on MediaWiki and that the macros were considered widely used. Now that Mathoid/mathjax-node is used on Wikipedia, that weighs even more heavily, I think, so I would be against removing it at this time. (See also https://github.com/mathjax/MathJax-node/issues/134, I guess.)

Still, I could easily imagine pushing it out again in v3.0 because I'd expect extensions to be just another module, thus npm dependency, so MediaWiki/Mathoid won't have a serious issue.

In any case, I had almost added `non-standard` already so I'm ok with adding it.

FWIW, there is http://ctan.org/pkg/texvc which should be identical (cf. the maintainer); on debian-derivatives it's part of texlive-latex-extra. So maybe we can call it "standard" even.

**Comment by dpvc** [comment]
OK, sounds reasonable.  I didn't know about the texvc CTAN module.  It is relatively new.  I'm willing to leave off the "non-standard", then.

**Comment by dpvc** [comment]
The only issue, then, is that the extension is actually `wikimedia-texvc` not just `texvc`.  I think all the other ones give the fill extension name.  Should the extension be renamed to match the CTAN one?

**Comment by pkra** [comment]
> Should the extension be renamed to match the CTAN one?

I would be in favor but I think this would be a breaking change (in semver terms) and thus would have to wait until v3.0. We could ask Moritz to rename the CTAN package ;-)

**Comment by pkra** [comment]
Also, I think we insisted on that prefix since texvc was too vague. :frowning:

**Comment by pkra** [comment]
I've added the mediawiki prefix to the list of macros. @dpvc ptal.

**Comment by dpvc** [comment]
@pkra, I'm fine with that.

**Pull request merged**
