### PR TITLE
[accessibility features] revise AssisiteMML description

### LINKED ISSUE #222: update accessibility-features
Would you be open to me re-writing this so that the a11y extensions are prominently mentioned as the real solution and the AssistiveMML is more strongly discouraged as a solution (e.g., likely to be deprecated in v3)? 

I've had one too many conversations where people skip over the a11y extension part and just read the details for AssistiveMML.js.

### PR DESCRIPTION
**Pull request by pkra**
Resolves #222

### CODE REVIEW

**Comment by pkra** [comment]
First attempt.

**Comment by dpvc** [comment]
These changes look reasonable.

If we strongly recommend not using the AssistiveMML extension, should it be removed from the combined configuration files?  It seems strange to depreciate it but still ship it with everything.  Alternatively, should more of the a11y extensions be included/enabled in the combined configurations?

**Comment by pkra** [comment]
> If we strongly recommend not using the AssistiveMML extension, should it be removed from the combined configuration files?

I wouldn't be against it but this might be considered a breaking change (requiring a major release according to semver); it depends if you consider the combined configurations as falling under semver.

>  should more of the a11y extensions be included/enabled in the combined configurations?

Since I don't use client-side rendering that much, I really can't weigh in here. I could imagine running SRE in a worker to generate labels might be ok. Or if it's not MathML, just use the source as label. I really don't know.

**Comment by pkra** [comment]
Ping.

**Comment by pkra** [comment]
Ping on this.

**Pull request closed without merging**
