### PR TITLE
Reorganise the page hierarchy

### PR DESCRIPTION
**Pull request by christianp**
At the moment, the nav menu contains 76 items, many of which have quite
long titles. It's hard to find the page I want.

There's a balance to be struck between menu depth and easy
discoverability of information, but this is definitely too far to one
extreme!

As a first pass, I've set the :caption: option on each of the toctrees,
replacing the manual headers on the index page, so a subsection heading
appears in the nav menu and not just on the index page.

The majority of the pages were configuration options pages. I've shoved
these into subdirectories, so only "configuration options" appears at
the root. I think this is reasonable - if you're trying to look up the
configurations for a particular output Jax, the "configuration options"
header would leap out at you.

I've also moved the "upgrading mathjax" pages into a subdirectory.

The "advanced topics" pages are too disparate to gather under one
heading, so I've left them as-is. I think the "basic usage" section
could do with some more organisation though - the "TeX and LaTeX"
support page, for example, isn't basic but is a pretty comprehensive
reference for the extensions and commands supported by the TeX input.

In my opinion, there should be a clear separation between "how do I do
this?" pages and reference pages. Many of the pages are walls of quite
technical exposition, hard to scan for the key bit of information needed
to get something done. Perhaps looking at the historical queries posted
to mathjax-users would be a good place to start a "how do I do this?"
section, allowing the rest of the docs to be rewritten as much more
structured reference information.

### CODE REVIEW

**Comment by christianp** [comment]
And if you accept this, you'll need to set up some redirects on readthedocs: http://read-the-docs.readthedocs.io/en/latest/user-defined-redirects.html

**Comment by pkra** [comment]
Thanks for this. I'll review when I get a chance to build it locally.

**Comment by pkra** [comment]
I like this. I also think this needs to be part of a larger re-organization. I would suggest to pull this into a separate branch here so it can be the basis of further re-organization.

**Comment by christianp** [comment]
I'm ready to look at this again. It looks like I've got write permission here - should I create a new branch?

**Comment by pkra** [comment]
> should I create a new branch?

Yes, please!

**Comment by christianp** [comment]
OK, I've created a branch `reorganise-2017`

**Comment by pkra** [comment]
Sorry, this broke during the necessary updates last week. I'll fix the PR once things have settled down with the CDN changes.

**Comment by pkra** [comment]
Rebasing on master is relatively painless -- just one conflict (installation.rst) in  that is easy to resolve (just pick newer).

@christianp do you want to confirm and update the branch? Alternatively, I can force push my resolution to this branch or push to a new one.

**Comment by pkra** [comment]
As per F2F, we have the go-ahead.

But we still need to add the redirect.s

**Comment by pkra** [comment]
Here's the hopefullly complete list:

R100    options/CHTML-preview.rst       options/extensions/CHTML-preview.rst
R100    options/Content-MathML.rst      options/extensions/Content-MathML.rst
R100    options/MML3.rst        options/extensions/MML3.rst
R093    options/a11y-extensions.rst     options/extensions/a11y-extensions.rst
R100    options/assistive-mml.rst       options/extensions/assistive-mml.rst
R100    options/fast-preview.rst        options/extensions/fast-preview.rst
R100    options/handle-floats.rst       options/extensions/handle-floats.rst
R100    options/AsciiMath.rst   options/input-processors/AsciiMath.rst
R100    options/MathML.rst      options/input-processors/MathML.rst
R098    options/TeX.rst options/input-processors/TeX.rst
R100    options/FontWarnings.rst        options/other/FontWarnings.rst
R100    options/MatchWebFonts.rst       options/other/MatchWebFonts.rst
R100    options/MathEvents.rst  options/other/MathEvents.rst
R100    options/MathMenu.rst    options/other/MathMenu.rst
R100    options/MathZoom.rst    options/other/MathZoom.rst
R100    options/Safe.rst        options/other/Safe.rst
R100    options/CommonHTML.rst  options/output-processors/CommonHTML.rst
R100    options/HTML-CSS.rst    options/output-processors/HTML-CSS.rst
R100    options/MMLorHTML.rst   options/output-processors/MMLorHTML.rst
R100    options/NativeMML.rst   options/output-processors/NativeMML.rst
R081    options/PlainSource.rst options/output-processors/PlainSource.rst
R100    options/PreviewHTML.rst options/output-processors/PreviewHTML.rst
R100    options/SVG.rst options/output-processors/SVG.rst
R100    options/asciimath2jax.rst       options/preprocessors/asciimath2jax.rst
R100    options/jsMath2jax.rst  options/preprocessors/jsMath2jax.rst
R100    options/mml2jax.rst     options/preprocessors/mml2jax.rst
R100    options/tex2jax.rst     options/preprocessors/tex2jax.rst
R096    jsMath.rst      upgrading/jsMath.rst
R093    upgrade.rst     upgrading/upgrade.rst
R100    whats-new-1.1.rst       upgrading/whats-new-1.1.rst
R100    whats-new-2.0.rst       upgrading/whats-new-2.0.rst
R100    whats-new-2.1.rst       upgrading/whats-new-2.1.rst
R100    whats-new-2.2.rst       upgrading/whats-new-2.2.rst
R100    whats-new-2.3.rst       upgrading/whats-new-2.3.rst
R100    whats-new-2.4.rst       upgrading/whats-new-2.4.rst
R100    whats-new-2.5.rst       upgrading/whats-new-2.5.rst
R100    whats-new-2.6.rst       upgrading/whats-new-2.6.rst
R100    whats-new-2.7.rst       upgrading/whats-new-2.7.rst

**Comment by pkra** [comment]
Redirects have been added in the readthedocs admin panel.

**Comment by pkra** [comment]
Thanks for your work on this and your patience, @christianp!

**Pull request merged**
