### PR TITLE
Minor - update CDN directory structure with latest version

### PR DESCRIPTION
**Pull request by Klortho**

### CODE REVIEW

**Comment by pkra** [comment]
Thanks again for catching this. Can you correct the comments for 2.4/2.5? Otherwise I can do it after merging.

**Comment by pkra** [comment]
Btw, since we version the documentation, the "at the time of this writing" isn't actually necessary (and it seems to me it doesn't compensate in case we forget to update the page for the next release)

**Comment by Klortho** [comment]
Done.

**Comment by pkra** [comment]
Awesome! Thanks!

**Pull request merged**
